[package]
name = "hecto"
version = "0.1.0"
edition = "2021"
authors = ["Joseph Bloom <joseph.i.bloom@gmail.com"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
unicode-segmentation = "1"